language: generic

services:
  - docker

before_install:
  - docker build -t ntdash/docker-react -f Dockerfile.test .

script:
  - docker run -e CI=true ntdash/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react"
  env: "React-env"
  bucket_name: "elasticbeanstalk-us-east-2-087098625966"
  bucket_path: "react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY