services:
  - docker

before_install:
  - docker build -t ntdash/docker-react -f Dockerfile.test .

script:
  - docker run ntdash/docker-react npm run test:ci

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-087098625966"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY